[gcp_service_account]
type = "service_account"
project_id = "tiendairsadosa"
private_key_id = "6696977631a523ea58b1c49ba68a2b08f7bd19c5"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BA...resto...\n-----END PRIVATE KEY-----\n"
client_email = "tienda-sheets-sa@tiendairsadosa.iam.gserviceaccount.com"
client_id = "111760285719661435545"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/tienda-sheets-sa%40tiendairsadosa.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

# 📊 Config de Google Sheets
SHEET_ID = "1YzLykO3weqGm2fQO_qtAwW2AKGH5oEPT"
SHEET_NAME = "TIENDA"

